services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      # - KC_HOSTNAME=localhost
      - KC_HTTP_ENABLED=true 
      # Dice a Keycloak: "No fuerces un nombre de host fijo, usa el que viene en la petición"
      - KC_HOSTNAME_STRICT=false 
      - KC_HOSTNAME_STRICT_HTTPS=false
    ports:
      - "8888:8080" # Mapea el puerto 8080 del contenedor al 8888 de tu máquina
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - transporte-net
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e \"GET /realms/master HTTP/1.1\r\nhost: localhost\r\nConnection: close\r\n\r\n\" >&3;cat <&3 | grep -q \"HTTP/1.1 200 OK\""]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 40s

  gestion:
    build: ./gestion
    container_name: gestion-service
    ports:
      - "8081:8081"
    # depends_on:
    #   - keycloak
    networks:
      - transporte-net
    # volumes:
      # - ./gestion-data:/app/data

  logistica:
    build: ./logistica
    container_name: logistica-service
    ports:
      - "8082:8082"
    # depends_on:
    #   - keycloak
    networks:
      - transporte-net
    # volumes:
      # - ./logistica-data:/app/data

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway-service
    ports:
      - "8080:8080"
    depends_on:
      gestion:
        condition: service_started
      logistica:
        condition: service_started
      keycloak:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY_OAUTH2=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY=DEBUG
      - LOGGING_LEVEL_ROOT=INFO
      # Asegurar conexión a Keycloak
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/tpi-backend/protocol/openid-connect/certs
    networks:
      - transporte-net
    

volumes:
  keycloak_data:
    driver: local

networks:
  transporte-net:
    driver: bridge